journal/urls.py
from django.urls import path
from . import views

app_name = 'journal'
urlpatterns = [
    path("", views.index, name="index" ),
    path("add/", views.add_journal, name="add_journal" ),
    path("delete/<int:journal_id>", views.delete_journal, name="delete_journal" ),
    path("edit/<int:journal_id>", views.edit_journal, name="edit_journal" ),
]

journalapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('journal.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path("auth/login", views.login_view, name="login_custom" ),
    path("auth/logout", views.logout_view, name="logout_custom" ),
    path("auth/signup", views.signup_view, name="signup_custom" ),
]

journal/models.py
from django.db import models
from django.contrib.auth.models import User


class Journal(models.Model):
    title = models.CharField(max_length=64)
    body = models.TextField()
    author_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name="journal_author", default=1)

    def __str__(self):
        return f"{self.title}: {self.body}"

users/models.py
from django.db import models

# Create your models here.

journal/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from .models import Journal

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login_custom'))
    journals = Journal.objects.all().filter(author_id=request.user.id)
    return render(request, 'journal/index.html', {'journals': journals})

def add_journal(request):
    title = request.POST['title']
    body = request.POST['body']
    try:
        Journal.objects.create(title=title, body=body, author_id=request.user)
    except KeyError:
        render(request, "journal/error.html", {"message": "Error Adding a Journal"})
    return HttpResponseRedirect(reverse('journal:index'))

def delete_journal(request, journal_id):
    try:
        journal = Journal.objects.get(pk=journal_id)
    except Journal.DoesNotExist:
        raise Http404("Journal does not exist.")
    journal.delete()
    return HttpResponseRedirect(reverse('journal:index'))

def edit_journal(request, journal_id):
    try:
        journal = Journal.objects.get(pk=journal_id)
    except Journal.DoesNotExist:
        raise Http404("Journal does not exist.")
    if request.method == "POST":
        journal.title = request.POST['title']
        journal.body = request.POST['body']
        journal.save()
        return HttpResponseRedirect(reverse('journal:index'))
    context = {
        'journal': journal
    }
    return render(request, "journal/edit.html", context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.models import User

def login_view(request):
    context = dict()
    if request.method == 'POST':
        try:
            username = request.POST['username']
            password = request.POST['password']
        except KeyError:
            context['error'] = "Wrong username/password"
            return render(request, 'users/login.html', context=context)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('journal:index',))
        context["error"] = "invalid credentials"
    return render(request, 'users/login.html', context=context)

def signup_view(request):
    context = dict()
    if request.method == 'POST':
        print("Using post method")
        try:
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            email = request.POST['email']
            username = request.POST['username']
            password = request.POST['password']
            confirm_password = request.POST['confirm_password']
        except KeyError:
            context['error'] = "Invalid input"
            return render(request, 'users/signup.html', context=context)
        if password != confirm_password:
            context['message'] = "Passwords Do not match!"
            return render(request, 'users/signup.html', context=context)
        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('journal:index',))
        context["error"] = "invalid credentials"
    return render(request, 'users/signup.html', context=context)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("journal:index"))

journal/templates/journal/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'journal/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,700' rel='stylesheet' type='text/css'>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

journal/templates/journal/edit.html
{% extends 'journal/base.html' %}

{% block title %}
    Journals
{% endblock %}
{% block body %}
    <div id="edit_page">
        <header class="container">
            <div class="row">
                <h4 class="col-sm-8">Edit Note</h1>
            </div>
        </header>
    
        {% if request.user.is_authenticated %}
        <div class="container">
            {% if error %}
                <p>{{ error }}
            {% endif %}
            <form action="{% url 'journal:edit_journal' journal.id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>Title:</label>
                    <input type="text" name="title" class="form-control" value="{{ journal.title }}" />
                </div>
                <div class="form-group">
                    <label>Body:</label>
                    <textarea type="text" name="body" class="form-control">{{ journal.body }}</textarea>
                </div>
                <input type="submit" value="Save" class="btn btn-primary"/>
            </form>
        </div>
        {% endif %}
{% endblock %}

journal/templates/journal/error.html
{% extends 'journal/base.html' %}
{% block title %}
    Error
{% endblock %}
{% block body %}
    {% if message %}
        {{ message }}
    {% endif %}
{% endblock %}

journal/templates/journal/index.html
{% extends 'journal/base.html' %}

{% block title %}
    Journals
{% endblock %}
{% block body %}
    <div id="page_wrap">
        <header class="container">
            <div class="row">
                <h4 class="col-sm-8">Digital Journal | Create A Note</h1>
                <nav class="col-sm-4">
                    {% if not user.is_authenticated %}
                        <p><a href="{% url 'users:login_custom' %}">Log In</a></p>
                        <p><a href="{% url 'users:signup_custom' %}">Sign Up</a></p>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <p><a href="{% url 'users:logout_custom' %}">Log Out</a></p>
                    {% endif %}
                </nav>
            </div>
        </header>
    
        {% if request.user.is_authenticated %}
        <div class="container">
            <form action="{% url 'journal:add_journal' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>Title:</label>
                    <input type="text" name="title" class="form-control"/>
                </div>
                <div class="form-group">
                    <label>Body:</label>
                    <textarea type="text" name="body" class="form-control"></textarea>
                </div>
                <p>Use the form above to create a post. Make sure you fill the title and body fields and press submit</p>
                <input type="submit" value="Submit" class="btn btn-primary">
            </form>
        </div>
        {% endif %}

        <div class="container flex">
            <div class="row">
                {% for journal in journals %}
                    <div class="col-sm-4">
                        <header class="container">
                            <div class="row">
                                <div class="col-sm-12">
                                    {{ journal.title }}
                                </div>
                            </div>
                        </header>
                        <div class="container">
                            <div class="row">
                                <p class="col-sm-12">
                                    {{ journal.body }}
                                </p>
                            </div>
                        </div>
                        <footer class="container">
                            <div class="row">
                                <p class="edit-journal col-sm-6"><a href="{% url 'journal:edit_journal' journal.id %}">Edit</a></p>
                                <p class="del-journal col-sm-6"><a href="{% url 'journal:delete_journal' journal.id %}">Delete</a></p>
                            </div>
                        </footer>
                    </div>
                {% endfor %}
            </div>    
        </div>
    </div>
{% endblock %}

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block head %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}">
    </head>
    <body>
        {% block body %}
        {% endblock %}    
    </body>
</html>

users/templates/users/login.html
{% extends "users/base.html" %}

{% block head %} 
    Login
{% endblock %}

{% block body %}
    <div class="main_page">
        <div class="container">
            <div class="row">
                <h4 class="container" style="text-align: center">Login</h4>
            </div>
        </div>
        {% if error %}
            <div>
                {{ error }}
            </div>
        {% endif %}
        <form action="{% url 'users:login_custom' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>Username</label>
                <input name="username" class="form-control" type="text" placeholder="username"/>
            </div>
            <div class="form-group">
                <label>Password</label>
                <input name="password" type="password" class="form-control" placeholder="password"/>
            </div>
            <div>
                <input type="submit" value="Login" class="btn btn-primary"/>
                <a href="{% url 'users:signup_custom' %}" class="btn btn-info">Signup</a>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/signup.html
{% extends 'users/base.html' %}

{% block head %}
    Signup
{% endblock %}

{% block body %}
    <div class="main_page">
        <h1 class="container" style="text-align: center">Signup</h1>
        {% if error %}
            <div>
                {{ error }}
            </div>
        {% endif %}
        <form action="{% url 'users:signup_custom' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>First Name</label>
                <input name="first_name" type="text" placeholder="e.g. John" class="form-control" required/>
            </div>

            <div class="form-group">
                <label>Last Name</label>
                <input name="last_name" type="text" placeholder="e.g. Name" class="form-control" required/>
            </div>

            <div class="form-group">
                <label>Email</label>
                <input name="email" type="email" placeholder="johndoe@gmail.com" class="form-control" required/>
            </div>

            <div class="form-group">
                <label>Username</label>
                <input name="username" type="text" placeholder="username" class="form-control" required/>
            </div>

            <div class="form-group">
                <label>Password</label>
                <input name="password" type="password" placeholder="password" class="form-control" required/>
            </div>
            
            <div class="form-group">
                <label>Confirm Password</label>
                <input name="confirm_password" type="password" placeholder="confirm password" class="form-control" required/>
            </div>
            
            <div class="footer">
                <input type="submit" value="Submit" class="btn btn-info"/>
                <a href="{% url 'users:login_custom' %}" class="btn btn-success">Login</a>
            </div>
        </form>
    </div>
{% endblock %}